module.exports = {
  UNVERIFY_ACCOUNT: "UNVERIFY_ACCOUNT",
  SUCCESS: "SUCCESS",
  CREATED: "CREATED",
  NO_CONTENT: "NO_CONTENT",
  BAD_REQUEST: "BAD_REQUEST",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  UNKNOWN_STATUS: "UNKNOWN_STATUS",
};
