module.exports = {
  licensesDefault: [
    {
      name: "Free",
      code: "DOWNLOAD_FREE",
      description: `Được update phiên bản mới\nDownload nhiều video với 1 click`,
      qty: 199,
      pricing: 0,
      pricingLabel: "Miễn phí",
      module: "DOWNLOAD",
      order: 1,
    },
    {
      name: "VIP 0",
      code: "DOWNLOAD_VIP_0",
      description: `Được update phiên bản mới\nDownload nhiều video với 1 click`,
      qty: 1499,
      pricing: 49000,
      pricingLabel: "49.000 VND",
      module: "DOWNLOAD",
      order: 2,
    },
    {
      name: "UNLIMITED",
      code: "DOWNLOAD_UNLIMITED",
      description: `Được update phiên bản mới\nDownload nhiều video với 1 click\nDownload video không giới hạn`,
      qty: -1,
      pricing: 349000,
      pricingLabel: "349.000 VND",
      module: "DOWNLOAD",
      order: 3,
    },
    {
      name: "Free",
      code: "PROFILE_FREE",
      description: `Được update phiên bản mới\nFree fingerprint`,
      qty: 2,
      pricing: 0,
      pricingLabel: "Miễn phí",
      module: "PROFILE",
      order: 1,
    },
    {
      name: "VIP MONTH 0",
      code: "PROFILE_VIP_MONTHLY_0",
      description: `Được update phiên bản mới\nFree fingerprint\nCài đặt video tải lên từ video đã edit\nAutomation upload video`,
      qty: 10,
      pricing: 199000,
      pricingLabel: "199.000 VND",
      module: "PROFILE",
      frequency: "MONTHLY",
      order: 2,
      expiryOn: "1 tháng",
    },
    {
      name: "VIP MONTH 1",
      code: "PROFILE_VIP_MONTHLY_1",
      description: `Được update phiên bản mới\nFree fingerprint\nCài đặt video tải lên từ video đã edit\nAutomation upload video`,
      qty: 30,
      pricing: 399000,
      pricingLabel: "399.000 VND/tháng",
      module: "PROFILE",
      frequency: "MONTHLY",
      order: 3,
      isPopular: true,
      expiryOn: "1 tháng",
    },
    {
      name: "VIP YEAR 0",
      code: "PROFILE_VIP_YEAR_0",
      description: `Được update phiên bản mới\nFree fingerprint\nCài đặt video tải lên từ video đã edit\nAutomation upload video`,
      qty: 10,
      pricing: 1788000,
      pricingLabel: "149.000 VND/tháng",
      module: "PROFILE",
      frequency: "YEARLY",
      order: 4,
      expiryOn: "1 năm",
    },
    {
      name: "VIP YEAR 1",
      code: "PROFILE_VIP_YEAR_1",
      description: `Được update phiên bản mới\nFree fingerprint\nCài đặt video tải lên từ video đã edit\nAutomation upload video`,
      qty: 30,
      pricing: 3588000,
      pricingLabel: "299.000 VND/tháng",
      module: "PROFILE",
      frequency: "YEARLY",
      order: 5,
      isPopular: true,
      expiryOn: "1 năm",
    },
    {
      name: "TÙY CHỈNH",
      code: "PROFILE_CUSTOM",
      description: `Được update phiên bản mới\nFree fingerprint\nCài đặt video tải lên từ video đã edit\nAutomation upload video`,
      qty: -1,
      pricing: 0,
      pricingLabel: "Liên hệ",
      module: "PROFILE",
      order: 6,
      expiryOn: "tùy chỉnh",
    },
    {
      name: "Free",
      code: "EDIT_VIDEO_FREE",
      description: `Được update phiên bản mới`,
      qty: 199,
      pricing: 0,
      pricingLabel: "Miễn phí",
      module: "EDIT_VIDEO",
      order: 1,
    },
    {
      name: "VIP 0",
      code: "EDIT_VIDEO_VIP_0",
      description: `Được update phiên bản mới\nChỉnh sửa nhiều video với 1 click\nLách bản quyền`,
      qty: 1499,
      pricing: 99000,
      pricingLabel: "99.000 VND",
      module: "EDIT_VIDEO",
      order: 2,
    },
    {
      name: "VIP 1",
      code: "EDIT_VIDEO_VIP_1",
      description: `Được update phiên bản mới\nChỉnh sửa nhiều video với 1 click\nLách bản quyền\nAuto sub video`,
      qty: 14999,
      pricing: 449000,
      pricingLabel: "449.000 VND",
      module: "EDIT_VIDEO",
      order: 3,
      isPopular: true,
    },
    {
      name: "UNLIMITED",
      code: "EDIT_VIDEO_UNLIMITED",
      description: `Được update phiên bản mới\nChỉnh sửa không giới hạn\nChỉnh sửa nhiều video với 1 click\nLách bản quyền\nAuto sub video`,
      qty: -1,
      pricing: 649000,
      pricingLabel: "649.000 VND",
      module: "EDIT_VIDEO",
      order: 4,
    },
  ],
};
